name: thingsboard_pe_client
description: Dart implementation of ThingsBoard PE API client.
version: 1.0.0
homepage: https://thingsboard.io

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  jwt_decoder: ^2.0.1
  web_socket_channel: ^2.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
